% Pivot table functions for matlab
% Tabulates arbitrary stats of data into tables depending, 
% on the independent variables that can be place in rows or columns.
%   author: Joern Diedrichsen
%   email: j.diedrichsen@bangor.ac.uk
% V.1.0: 9/03/05
% V.2.0: 29/08/07
% V.2.2: 07/08/09
% 1. Pivot Table Functions 
%   pivottable      - All-purpose pivot table for tabulation
%   tapply          - Condenses a Data structure into another
% 2. Utility functions  
%   pidata          - Sorts the data into an cell-array
%   print_pivot     - Formated output on screen
%   fac2int         - Conversion of string-valued variable (factor) into intergers 
%   int2fac         - Backwards conversion
% 3. Example function for field commands
%   corr            - Correlation
%   stderr          - Standard error (sd/sqrt(N))
